# Path related
dataset_path: data/raw/bank.csv
dataset_cleaned_path: data/processed/data.pkl
train_set_path:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
valid_set_path:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
test_set_path:
- data/processed/x_test.pkl
- data/processed/y_test.pkl
train_feng_set_path:
- data/processed/x_train_feng.pkl
- data/processed/y_train_feng.pkl
valid_feng_set_path:
- data/processed/x_valid_feng.pkl
- data/processed/y_valid_feng.pkl
test_feng_set_path:
- data/processed/x_test_feng.pkl
- data/processed/y_test_feng.pkl
production_model_path: Model/production_model.pkl
ohe_stasiun_path: Model/ohe_stasiun.pkl
le_encoder_path: Model/le_encoder.pkl
training_log_path: log/training_log.json

# Debug related
print_debug: true

# missing values imputation
balance_imputation: 550
pdays_imputation: 0

# drop high cardinality features
drop_list:
- day
- month
- job

int32_columns:
- age
- balance
- day
- duration
- campaign
- pdays
- previous
label: deposit
label_deposit:
- "no"
- "yes"
label_deposit_new:
- "no"
- "yes"
missing_value_pdays: 0
missing_value_balance: 630
object_columns:
- job
- marital
- education
- default
- housing
- loan
- contact
- month
- poutcome
- deposit

predictors:
- age
- marital
- education
- default
- balance
- housing
- loan
- contact
- duration
- campaign
- pdays
- previous
- poutcome
- day
- job
- month

predictors_ohe:
- age 
- balance
- duration
- campaign
- pdays
- previous
- marital_married
- marital_single
- education_secondary
- education_tertiary
- education_unknown
- default_yes
- housing_yes
- loan_yes
- contact_telephone
- contact_unknown
- poutcome_other
- poutcome_success
- poutcome_unknown

range_age:
- 18
- 95
range_balance:
- -1
- 81204
range_day:
- 1
- 31
range_duration:
- 2
- 3881
range_campaign:
- 1
- 63
range_pdays:
- -1
- 854
range_previous:
- 0
- 58
range_job:
- admin.
- technician
- services
- management
- retired
- blue-collar
- unemployed
- entrepreneur
- housemaid
- unknown
- self-employed
- student
range_marital:
- married
- single
- divorced
range_education:
- secondary
- tertiary
- primary
- unknown
range_default:
- "no"
- "yes"
range_housing:
- "no"
- "yes"
range_loan:
- "no"
- "yes"
range_contact:
- unknown
- cellular
- telephone
range_month:
- jan
- feb
- mar
- apr
- may
- jun
- jul
- aug
- sep
- oct
- nov
- dec
range_poutcome:
- unknown
- other
- failure
- success
range_deposit:
- "yes"
- "no"

# Splitting related
test_size: 0.3
valid_size: 0.5